apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: debian-app-locked-manual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian-app
  template:
    metadata:
      annotations:
        # The podspec annotation is still needed by the podwatch controller.
        "initializer.kubernetes.io/tproxy": "true"
      labels:
        app: debian-app
        variant: locked
    spec:
      initContainers:
        - name: tproxy
          image: danisla/tproxy-sidecar:0.1.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
      containers:
        - name: app
          image: danisla/example-app:debian
          imagePullPolicy: Always
          volumeMounts:
            - name: ca-certs-debian
              mountPath: /etc/ssl/certs/
            - name: ca-certs-debian
              # Adding the cert to the /extra dir preserves it if update-ca-certificates is run after init.
              mountPath: /usr/local/share/ca-certificates/extra/
      volumes:
        - name: ca-certs-debian
          configMap:
              name: tproxy-mitmproxy-root-certs
              items:
                - key: root-certs.crt
                  path: ca-certificates.crt