apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: centos-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos-app
  template:
    metadata:
      labels:
        app: centos-app
        variant: unlocked
    spec:
      containers:
        - name: app
          image: danisla/example-app:centos
          imagePullPolicy: Always