apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: centos-app-locked
  annotations:
    "initializer.kubernetes.io/tproxy": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos-app
  template:
    metadata:
      labels:
        app: centos-app
        variant: locked
    spec:
      containers:
        - name: app
          image: danisla/example-app:centos
          imagePullPolicy: IfNotPresent