apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: debian-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian-app
  template:
    metadata:
      labels:
        app: debian-app
        variant: unlocked
    spec:
      containers:
        - name: app
          image: danisla/example-app:debian
          imagePullPolicy: IfNotPresent