# Default values for tproxy-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: danisla/example-app
  tag: debian
  pullPolicy: IfNotPresent

# Obtain the values for blockSvcCIDR and allowDNS using these commands:
#   CLUSTER=dev
#   SVC_CIDR=$(gcloud container clusters describe $CLUSTER --zone us-central1-c --format='value(servicesIpv4Cidr)')
#   DNS_IP=$(kubectl get svc kube-dns -n kube-system -o jsonpath="{.spec.clusterIP}")
#   NUM_NODES=$(gcloud container clusters describe $CLUSTER --zone us-central1-c --format='value(currentNodeCount)')
#
blockSvcCIDR:
allowDNS:
numNodes:

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
